[package]
name = "gpui_tesserae"
version = "0.1.1"
edition = "2024"

[dependencies]
# gpui_transitions = { git = "https://github.com/astrum-chat/gpui_tesserae" }
# Local development.
gpui_transitions = { path = "./crates/gpui_transitions" }

gpui = "0.2.2"
gpui_squircle = "1.0.1"
smallvec = { version = "1.15.1", features = ["serde"] }
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
anyhow = "1.0.100"
cfg-if = "1.0.4"
enum-assoc = "1.2.4"

# Input component.
unicode-segmentation = "1.12.0"

# Assets feature.
rust-embed = { version = "8.9.0", optional = true }

[features]
default = ["assets"]
assets = ["dep:rust-embed"]

[workspace]
members = [
    "crates/gpui_transitions"
]
