[package]
name = "gpui_primitives"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { workspace = true }
smallvec = { workspace = true }
unicode-segmentation = { workspace = true }

[features]
default = []
test-support = ["gpui/test-support"]

[dev-dependencies]
