[package]
name = "gpui_tesserae_theme"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = "0.2.2"
smallvec = { version = "1.15.1", features = ["serde"] }
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
